lib/loor_web/router.ex
defmodule LoorWeb.Router do
  use LoorWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LoorWeb do
    pipe_through :browser

    get "/", LandingController, :index
    post "/email", EmailController, :add
    get "/view/:slug", LandingController, :view
    get "/landing/:id/emails", LandingController, :emails
    resources "/landing", LandingController
  end

  # Other scopes may use custom stacks.
  # scope "/api", LoorWeb do
  #   pipe_through :api


  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LoorWeb.Telemetry
    end
  end
end

lib/loor/application.ex
defmodule Loor.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Loor.Repo,
      # Start the Telemetry supervisor
      LoorWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Loor.PubSub},
      # Start the Endpoint (http/https)
      LoorWeb.Endpoint
      # Start a worker by calling: Loor.Worker.start_link(arg)
      # {Loor.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Loor.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    LoorWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/loor/email.ex
defmodule Loor.Email do
  use Ecto.Schema
  import Ecto.Changeset

  schema "emails" do
    field :email, :string
    field :landing_id, :id

    timestamps()
  end

  @doc false
  def changeset(email, attrs) do
    email
    |> cast(attrs, [:email, :landing_id])
    |> validate_required([:email, :landing_id])
  end
end

lib/loor/landing.ex
defmodule Loor.Landing do
  use Ecto.Schema
  import Ecto.Changeset

  schema "landings" do
    field :button_text, :string
    field :call_to_action, :string
    field :header_text, :string
    field :slug, :string
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(landing, attrs \\ %{}) do
    landing
    |> cast(attrs, [:title, :header_text, :call_to_action, :slug, :button_text])
    |> validate_required([:title, :header_text, :call_to_action, :slug, :button_text])
  end
end

lib/loor/repo.ex
defmodule Loor.Repo do
  use Ecto.Repo,
    otp_app: :loor,
    adapter: Ecto.Adapters.Postgres
end

lib/loor_web/controllers/email_controller.ex
defmodule LoorWeb.EmailController do
  use LoorWeb, :controller

  import Ecto.Query

  alias Loor.{Repo, Email, Landing}

  def add(conn, %{"email" => email }) do

    %{"landing_id" => id, "email" => email, "slug" => slug} = email
    id = String.to_integer(id)

    [%Landing{} = landing] = Landing |> where(slug: ^slug) |> Repo.all

    changeset = Email.changeset(%Email{}, %{"email" => email, "landing_id" => id})

    case Repo.insert(changeset) do
      {:ok, _landing} ->
        conn
        |> put_flash(:info, "Thank you for signing up!")
        |> redirect(to: "/view/#{slug}")
      {:error, changeset} ->
        render conn, "show_view.html"
  end
end
end

lib/loor_web/controllers/landing_controller.ex
defmodule LoorWeb.LandingController do
  use LoorWeb, :controller


  import Ecto.Query

  alias Loor.{Landing, Repo, Email}


  def index(conn, _params) do
    landings = Repo.all(Landing)

    render conn, "index.html", landings: landings
  end

  def emails(conn, %{"id" => landing_id}) do
    emails = Email |> where(landing_id: ^landing_id) |> Repo.all

    render conn, "emails.html", emails: emails
  end

  def show(conn, %{"id" => landing_id}) do
    landing = Repo.get(Landing, landing_id)
    changeset = Email.changeset(%Email{}, %{})

    render conn, "show.html", changeset: changeset, landing: landing
  end

  def view(conn, %{"slug" => slug}) do
    [%Landing{} = landing] = Landing |> where(slug: ^slug) |> Repo.all
    changeset = Email.changeset(%Email{}, %{})

    render conn, "show_view.html", changeset: changeset, landing: landing
  end

  def new(conn, _params) do
    changeset = Landing.changeset(%Landing{}, %{})

    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"landing" => landing}) do
    changeset = Landing.changeset(%Landing{}, landing)

    case Repo.insert(changeset) do
      {:ok, _landing} ->
        conn
        |> put_flash(:info, "Landing Created")
        |> redirect(to: Routes.landing_path(conn, :index))
      {:error, changeset} ->
        render conn, "new.html", changeset: changeset
    end
  end

  def edit(conn, %{"id" => landing_id}) do
    landing = Repo.get(Landing, landing_id)
    changeset = Landing.changeset(landing)

    render conn, "edit.html", changeset: changeset, landing: landing
  end

  def update(conn, %{"landing" => landing, "id" => landing_id}) do
    current_landing = Repo.get(Landing, landing_id)
    changeset = Landing.changeset(current_landing, landing)

    case Repo.update(changeset) do
      {:ok, _landing} ->
        conn
        |> put_flash(:info, "Landing Updated")
        |> redirect(to: Routes.landing_path(conn, :index))
      {:error, changeset} ->
        render conn, "edit.html", changeset: changeset, landing: current_landing
    end
  end



  def delete(conn, %{"id" => landing_id}) do
    Repo.get!(Landing, landing_id)
    |> Repo.delete!

    conn
    |> put_flash(:info, "Landing Deleted")
    |> redirect(to: Routes.landing_path(conn, :index))

  end

end

lib/loor_web/views/email_view.ex
defmodule LoorWeb.EmailView do
  use LoorWeb, :view
end

lib/loor_web/views/error_view.ex
defmodule LoorWeb.ErrorView do
  use LoorWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".

  # def render("404.html", _assigns) do
  #   "Page Not Found"
  # end

  # def template_not_found(template, _assigns) do
  #   Phoenix.Controller.status_message_from_template(template)
  # end


end

lib/loor_web/views/landing_view.ex
defmodule LoorWeb.LandingView do
  use LoorWeb, :view
end

lib/loor_web/views/layout_view.ex
defmodule LoorWeb.LayoutView do
  use LoorWeb, :view
end

lib/loor_web/views/page_view.ex
defmodule LoorWeb.PageView do
  use LoorWeb, :view
end

lib/loor_web/templates/landing/edit.html.eex
<h1 class="my-8 text-3xl font-bold text-center text-yellow-500">Update Landing</h1>

<%= form_for @changeset, Routes.landing_path(@conn, :update, @landing), [class: "w-1/4"], fn f -> %>
    <div class="flex flex-col w-full space-y-3 text-black form-group">
        <%= text_input f, :title, placeholder: "title", class: "form-control rounded-md p-2 " %>
        <%= error_tag f, :title %>
        <%= textarea f, :header_text, placeholder: "Header", class: "form-control p-2 rounded-md", rows: 5 %>
        <%= error_tag f, :header_text %>
        <%= textarea f, :call_to_action, placeholder: "Call to Action", class: "p-2 form-control rounded-md", rows: 3 %>
        <%= error_tag f, :call_to_action %>
        <%= text_input f, :button_text, placeholder: "button text", class: "p-2 form-control rounded-md" %>
        <%= error_tag f, :button_text %>
        <%= hidden_input f, :slug %>

        <div class="flex space-x-2 text-center text-white">
            <%= link  "Cancel", to: Routes.landing_path(@conn, :index), class: "form-control rounded-md w-1/4 h- bg-green-500 p-4 text-md my-4"%>
            <%= submit "Update", class: "form-control rounded-md w-3/4  bg-yellow-500 p-4 text-md my-4" %>
        </div>
    </div>
<% end %>

lib/loor_web/templates/landing/emails.html.eex
<h2 class="my-4 text-3xl font-bold text-center text-yellow-500">Emails</h2>
<ul class="container flex flex-col items-center justify-center space-y-2">
    <%= for email <- @emails do %>
        <li class="flex justify-between w-1/2 p-2 text-white border rounded-md">
            <%= email.email %>
        </li>
        <% end %>
    <%= link  "Go Back", to: Routes.landing_path(@conn, :index), class: "form-control rounded-md w-1/4 text-center text-yellow-500 hover:underline p-4 text-md my-4"%>
</ul>

lib/loor_web/templates/landing/index.html.eex
<h2 class="my-4 text-3xl font-bold text-center text-yellow-500">Landings</h2>

<%= link "Create new landing", to: Routes.landing_path(@conn, :new), class: "p-2 mb-4 text-white bg-yellow-500 rounded-md"  %>

<ul class="container flex flex-col items-center justify-center space-y-2">
    <%= for landing <- @landings do %>
        <li class="flex justify-between w-1/2 p-2 text-white border rounded-md">
            <%= landing.title %>
        <div class="space-x-2 text-yellow-400 text-bl">
            <%= link "Preview", to: Routes.landing_path(@conn, :show, landing) %>
            <%= link "Share", to: "/view/#{landing.slug}" %>
            <%= link "Emails", to: Routes.landing_path(@conn, :emails, landing) %>
            <%= link "Edit", to: Routes.landing_path(@conn, :edit, landing) %>
            <%= link "Delete", to: Routes.landing_path(@conn, :delete, landing), data: [confirm: "Are you sure you want to delete this Landing? You'll lose the entire email list."], method: :delete %>
            </div>
        </li>
    <% end %>
</ul>

lib/loor_web/templates/landing/new.html.eex
<h1 class="my-8 text-3xl font-bold text-center text-yellow-500">Create New Landing</h1>

<%= form_for @changeset, Routes.landing_path(@conn, :create), [class: "w-1/4"], fn f -> %>
    <div class="flex flex-col w-full space-y-3 text-black form-group">
        <%= text_input f, :title, placeholder: "title", class: "form-control rounded-md p-2 " %>
        <%= error_tag f, :title %>
        <%= textarea f, :header_text, placeholder: "Header", class: "form-control p-2 rounded-md", rows: 5 %>
        <%= error_tag f, :header_text %>
        <%= textarea f, :call_to_action, placeholder: "Call to Action", class: "p-2 form-control rounded-md", rows: 3 %>
        <%= error_tag f, :call_to_action %>
        <%= text_input f, :button_text, placeholder: "button text", class: "p-2 form-control rounded-md" %>
        <%= error_tag f, :button_text %>
        <%= hidden_input f, :slug, value: Nanoid.generate() %>

        <div class="flex space-x-2 text-center text-white">
            <%= link  "Cancel", to: Routes.landing_path(@conn, :index), class: "form-control rounded-md w-1/4 h- bg-green-500 p-4 text-md my-4"%>
            <%= submit "Create", class: "form-control rounded-md w-3/4  bg-yellow-500 p-4 text-md my-4" %>
        </div>
    </div>
<% end %>

lib/loor_web/templates/landing/show.html.eex
<h1 class="my-8 text-3xl font-bold text-center text-yellow-500"><%= raw @landing.header_text %></h1>
<p class="text-lg text-center text-white"><%= raw @landing.call_to_action %></p>

<%= form_for @changeset, Routes.email_path(@conn, :add), fn f -> %>
    <div class="flex flex-row justify-center my-8 text-black">
        <%= email_input f, :email, placeholder: "email address", class: "  mr-6 px-4 py-2 rounded", disabled: true %>
        <%= submit @landing.button_text, class: "px-4 text-gray-900 bg-yellow-500 rounded", disabled: true %>
        <%= hidden_input f, :landing_id, value: @landing.id %>
    </div>
<% end %>

<%= link  "Go Back", to: Routes.landing_path(@conn, :index), class: "form-control rounded-md w-1/4 text-center text-yellow-500 hover:underline p-4 text-md my-4"%>

lib/loor_web/templates/landing/show_view.html.eex
<h1 class="my-8 text-3xl font-bold text-center text-yellow-500"><%= raw @landing.header_text %></h1>
<p class="text-lg text-center text-white"><%= raw @landing.call_to_action %></p>

<%= form_for @changeset, Routes.email_path(@conn, :add), fn f -> %>
    <div class="flex flex-row justify-center my-8 text-black">
        <%= email_input f, :email, placeholder: "email address", class: "  mr-6 px-4 py-2 rounded", required: true %>
        <%= hidden_input f, :slug, value: @landing.slug %>
        <%= hidden_input f, :landing_id, value: @landing.id %>
        <%= submit @landing.button_text, class: "px-4 text-gray-900 bg-yellow-500 rounded"%>
    </div>
<% end %>

lib/loor_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Loor · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
  <p class="absolute w-screen p-8 text-white bg-blue-800 alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <main class="flex flex-col items-center justify-center w-screen h-screen p-16 overflow-hidden font-serif text-white bg-gray-900" role="main">

      <%= @inner_content %>
    </main>
  </body>
</html>